-- What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd)AS Revenue 
FROM customer_behaviour GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd 
FROM customer_behaviour WHERE discount_applied = "Yes" 
AND purchase_amount_usd>= (SELECT AVG(purchase_amount_usd) FROM customer_behaviour) ;

-- Which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating), 2) as "Average Rating Product" 
FROM customer_behaviour GROUP BY item_purchased ORDER BY AVG(review_rating) DESC LIMIT 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount_usd),2) AS "Shipping Type" 
FROM customer_behaviour  WHERE shipping_type in ("Express","Standard") GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subcribers and non-subscribers.
SELECT subscription_status, 
COUNT(customer_id) AS "Total Customer", 
ROUND(AVG(purchase_amount_usd),2) as Average_Spending,
ROUND(SUM(purchase_amount_usd),2) as Total_Revenue FROM customer_behaviour
GROUP BY subscription_status ORDER BY Average_Spending,Total_Revenue;

-- Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_behaviour 
GROUP BY item_purchased ORDER BY discount_rate DESC LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each statement.
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN "New"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "Return"
ELSE "Loyal" END AS customer_segment
FROM customer_behaviour
)
SELECT customer_segment, count(*) as number_of_customer FROM customer_type GROUP BY customer_segment;

-- What are the top 3 most purchased products within each category?
WITH RankedProducts AS (
SELECT 
category,
item_purchased,
COUNT(*) AS total_purchases,
ROW_NUMBER() OVER (
PARTITION BY category 
ORDER BY COUNT(*) DESC
) AS rank_num
FROM customer_behaviour
GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchases
FROM RankedProducts
WHERE rank_num <= 3
ORDER BY category, rank_num;
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT COUNT(*) AS repeat_buyer, 
subscription_status FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group?
SELECT age_group,
ROUND(SUM(purchase_amount_usd),2) AS total_revenue
FROM customer_behaviour GROUP BY age_group ORDER BY total_revenue DESC;